---
# MegaLinter Configuration
# https://megalinter.io
APPLY_FIXES: all
ENABLE_LINTERS:
  - TERRAFORM_TFLINT
  - TERRAFORM_TERRAFORM_VALIDATE
  - TERRAFORM_TERRASCAN
  - CLOUDFORMATION_CFN_LINT
  - YAML_YAMLLINT
  - JAVASCRIPT_ES
  - BASH_SHELLCHECK
  - MARKDOWN_MARKDOWNLINT
  - JSON_JSONLINT
  - DOCKERFILE_HADOLINT
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - SPELL_CSPELL
  - SPELL_MISSPELL
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PRINT_ALL_FILES: false
TERRAFORM_TFLINT_CONFIG_FILE: .tflint.hcl
JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
FILTER_REGEX_EXCLUDE: "(node_modules|\.terraform|\.git)"
