#!/usr/bin/env bash
# =============================================================================
# Entrypoint — Rippled Validator Node
# =============================================================================
# 1. Injects validator_token from Secrets Manager (via ECS secrets injection)
# 2. Writes validators.txt with private network UNL
# 3. Configures [ips_fixed] peer discovery
# 4. Sets [network_id] for private network isolation
# 5. Starts rippled in foreground
# =============================================================================
set -euo pipefail

CONFIG_FILE="/etc/opt/ripple/rippled.cfg"
VALIDATORS_FILE="/etc/opt/ripple/validators.txt"

echo "[entrypoint] Starting rippled validator node..."

# ─────────────────────────────────────────────────────────────────────────────
# 1. Inject validator_token (base64 blob generated by validator-keys tool)
#    This is the correct method per xrpl.org private network docs.
#    VALIDATION_SEED (legacy) is NOT used.
# ─────────────────────────────────────────────────────────────────────────────
if [ -n "${VALIDATOR_TOKEN:-}" ]; then
  echo "[entrypoint] Injecting validator_token from Secrets Manager"
  sed -i "s/PLACEHOLDER_INJECT_AT_DEPLOY/${VALIDATOR_TOKEN}/" "${CONFIG_FILE}"
elif [ -n "${VALIDATION_SEED:-}" ]; then
  # Fallback: legacy validation_seed support
  echo "[entrypoint] WARN: Using legacy validation_seed (prefer validator_token)"
  # Replace [validator_token] section with [validation_seed]
  sed -i "s/\[validator_token\]/[validation_seed]/" "${CONFIG_FILE}"
  sed -i "s/PLACEHOLDER_INJECT_AT_DEPLOY/${VALIDATION_SEED}/" "${CONFIG_FILE}"
else
  echo "[entrypoint] ERROR: Neither VALIDATOR_TOKEN nor VALIDATION_SEED is set"
  exit 1
fi

# ─────────────────────────────────────────────────────────────────────────────
# 2. Write validators.txt (private network UNL)
#    Forcefully overwrite the default mainnet validators.txt from the package.
# ─────────────────────────────────────────────────────────────────────────────
# Blank out any existing validators.txt first (mainnet default from package)
: > "${VALIDATORS_FILE}" 2>/dev/null || true

if [ -n "${VALIDATOR_PUBLIC_KEYS:-}" ]; then
  echo "[entrypoint] Writing validators.txt"
  {
    echo "[validators]"
    IFS=',' read -ra KEYS <<< "${VALIDATOR_PUBLIC_KEYS}"
    for key in "${KEYS[@]}"; do
      trimmed=$(echo "${key}" | tr -d '[:space:]')
      [ -n "${trimmed}" ] && echo "    ${trimmed}"
    done
  } > "${VALIDATORS_FILE}"
  echo "[entrypoint]   → ${#KEYS[@]} validators configured"
else
  # Write an empty [validators] block so rippled uses NO external UNL
  echo "[entrypoint] WARN: VALIDATOR_PUBLIC_KEYS not set — writing empty validators.txt"
  echo "[validators]" > "${VALIDATORS_FILE}"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 3. Configure [ips_fixed] peer discovery
#    PEER_IPS: comma-separated list e.g. "ripple-validator.dev.local 51235,..."
# ─────────────────────────────────────────────────────────────────────────────
if [ -n "${PEER_IPS:-}" ]; then
  echo "[entrypoint] Configuring peer discovery"
  {
    echo ""
    echo "[ips_fixed]"
    IFS=',' read -ra PEERS <<< "${PEER_IPS}"
    for peer in "${PEERS[@]}"; do
      trimmed="${peer#"${peer%%[![:space:]]*}"}"
      [ -n "${trimmed}" ] && echo "${trimmed}"
    done
  } >> "${CONFIG_FILE}"
  echo "[entrypoint]   → ${#PEERS[@]} fixed peers configured"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 4. Set [network_id] for private network isolation (prevents mainnet connect)
# ─────────────────────────────────────────────────────────────────────────────
if [ -n "${NETWORK_ID:-}" ]; then
  {
    echo ""
    echo "[network_id]"
    echo "${NETWORK_ID}"
  } >> "${CONFIG_FILE}"
  echo "[entrypoint] Network ID set to ${NETWORK_ID}"
fi

# ─────────────────────────────────────────────────────────────────────────────
# 5. Wait for peer DNS to be populated before starting rippled
#    Prevents ledger divergence from validators starting before peers register
# ─────────────────────────────────────────────────────────────────────────────
if [ -n "${PEER_IPS:-}" ]; then
  # Extract the first DNS name from PEER_IPS (format: "hostname port,hostname2 port")
  PEER_DNS=$(echo "${PEER_IPS}" | cut -d',' -f1 | awk '{print $1}')
  EXPECTED_PEERS="${EXPECTED_PEER_COUNT:-3}"  # includes self
  echo "[entrypoint] Waiting for peer DNS (${PEER_DNS}) to return ${EXPECTED_PEERS} records..."

  for attempt in $(seq 1 30); do
    RESOLVED=$(getent ahosts "${PEER_DNS}" 2>/dev/null | awk '{print $1}' | sort -u | wc -l || echo "0")
    RESOLVED=$(echo "${RESOLVED}" | tr -d ' ')
    if [ "${RESOLVED}" -ge "${EXPECTED_PEERS}" ] 2>/dev/null; then
      echo "[entrypoint] ✅ DNS ready: ${RESOLVED} peers found"
      break
    fi
    echo "[entrypoint]   [${attempt}/30] ${RESOLVED}/${EXPECTED_PEERS} peers — retrying in 5s..."
    sleep 5
  done
fi

# ─────────────────────────────────────────────────────────────────────────────
# 6. Start rippled
# ─────────────────────────────────────────────────────────────────────────────
echo "[entrypoint] Configuration complete. Starting rippled..."
echo "[entrypoint]   Config: ${CONFIG_FILE}"
echo "[entrypoint]   Role: validator"

exec rippled --conf "${CONFIG_FILE}" --fg

